### ISSUE TITLE
Incorrect Gauge Deposit Fees

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-backend#10]
These pools have incorrect gauge deposit fees:

**VRTK-WBNB:** Shows 1%/1% - should be 0%/0%
**BUSD-USDC-USDT:** Shows 1%/1% - should be 0%/0%
**SWDB-ETH:** Shows 1%/1% - should be 0%/0%
**TUSD-DAI-FRAX-BUSD:** Shows 1%/1% - should be 0%/0%
**WBNB-BUSD:** Shows 1%/1% - should be 0%/0%
**CHAM-SDHB-WBNB:** Shows 1%/1% - should be 0%/0%
**WBNB-USDC:** Shows 1%/1% - should be 0%/0%
**WETH-WBTC-WBNB:** Shows 1%/1% - should be 0%/0%

**Comment by 0xBriz** [comment]
This was a UI issue. Fees are set correctly. Frontend has been updated
