### ISSUE TITLE
Incorrect Gauge Deposit Fees

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-backend#11]
Still a few gauges with incorrect fees:

**UP-BUSD (Only UP):** Shows 0%/0% should be 1%/1%
**SRN-ETH (Pure Serenity):** Shows 0%/0% should be 1%/1%
**wAALTO-BUSD (Aaltonian Avatar)**: Shows 0%/0% should be 1%/1%
**LSHARE-DAI (Lion's Den):** Shows 0%/0% should be 1%/1%

**Comment by 0xBriz** [comment]
fixed
