### ISSUE TITLE
Vi Vertek Vincit doesn't accept BNB only.

### ISSUE THREAD

**Issue by Thefox797** [vertekfi/dex-backend#16]
The Vi Vertek Vincit pool has a issue when using normal BNB.

Investing through customize my investment with Vertek works: https://bscscan.com/tx/0x11357db915a88725794109d16c660cc88ad900c3158adf3868239d88003789ab

Investing with BNB (not wBNB) doens't work: https://bscscan.com/tx/0x56c19b13f58c93fb4a0f3261eafc56bb64d4e28de7cf8cb5a63784589c40fb07
It says succesfull invested but doesn't take the BNB out of the wallet or reward VPT's. Seems to be reverting maybe that's why it shows up as a withdrawal on the "investments tab"
![image](https://user-images.githubusercontent.com/124088392/216599940-df31e547-e249-49e5-96e8-a238e129ce22.png)

Investing Proportionally works: https://bscscan.com/tx/0x6eb09ccedb773c888ead1b5e36876239dd660966cd786856ee0848e113f4ccb4

I got the feeling this has to do with the routing from BNB --> wBNB --> Vertek. The DEX doesn't know the BNB --> wBNB route.

**Comment by 0xKang** [comment]
Update: I've realized this is an issue on any pool with BNB in it, not just the main pool.

**Comment by Thefox797** [comment]
The addition of BNB in the swap page doesn't seem to have fixed this yet. See txn below i zapped in with only BNB:
https://bscscan.com/tx/0xa25035439819e7021de0e3d2e902f8699e967e44d3460807b4283258462564e7

**Comment by 0xKang** [comment]
This issue has been resolved. @0xBriz Sgt Mjr sir 🖖
