### ISSUE TITLE
UP pool broken

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-backend#20]
**Pool Contract:** 0x64bf08FAC067b25C77967AFfaFcE73760d8D0BDF
**VPT Symbol:** 50UP-50BUSD

The UP-BUSD pool cannot be voted on. Clicking the **Confirm Vote** button does nothing. Console Returns json rpc error.

![image](https://user-images.githubusercontent.com/106936065/216826190-6f511487-f5f0-419e-8dde-63d02b6fc73c.png)
![image](https://user-images.githubusercontent.com/106936065/216826226-9c9566bb-6b21-4cf0-916f-e681f67107a4.png)

---

UP also has no price (we are the first liquidity pool, so theres no dexscreener or anything). Perhaps that's why.

**UP Token:** 0x5376A83112100Ff1567b2782e0d99c6d949b5509

![image](https://user-images.githubusercontent.com/106936065/216826304-5ebee12d-8d7e-428e-b3ad-75f8b9bb1f1a.png)
![image](https://user-images.githubusercontent.com/106936065/216826324-4874a6f8-6745-4830-a9f2-512917873f06.png)

---

Swapping is also currently not possible with UP. Even the smallest value does not light up the **Review Swap** button.

![image](https://user-images.githubusercontent.com/106936065/216826599-99f85049-e6b1-4f87-8cc9-f8e3c819f457.png)

**Comment by 0xBriz** [comment]
Voting issue fixed

![image](https://user-images.githubusercontent.com/98397602/217105011-490867e1-17e1-4c96-ac56-03dd850f326a.png)

**Comment by 0xBriz** [comment]
![image](https://user-images.githubusercontent.com/98397602/217105752-482860d0-a260-4aa0-81bd-308b6bf7c364.png)

**Comment by 0xBriz** [comment]
![image](https://user-images.githubusercontent.com/98397602/217105827-0ebe3d5d-e7bb-4f19-b289-7d585a74480d.png)
