### ISSUE TITLE
SHDB-CHAM-BNB pool broken

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-backend#21]
**### SHDB-CHAM-BNB (Shield of Seigniorage)**

- Users are unable to stake in the SHDB-CHAM-BNB pool
- Returns "resolver or addr is not configured for ENS name"
- This pool also does not show up on the **Claim** and **Vote** pages

Pool Contract: 0x7278A73aF8c788AF1e2f53b7BCc138B4F641BE35
VPT Symbol: 70SHDB-15CHAM-15BNB

![image](https://user-images.githubusercontent.com/106936065/216826955-36ed9fcd-48dd-4c3c-bf27-22c84279ebb6.png)

**Comment by 0xBriz** [comment]
![image](https://user-images.githubusercontent.com/98397602/217104073-8f4d10b3-e246-430c-a26c-c58bd532d131.png)
