### ISSUE TITLE
BNB & WBNB is not swappable (HIGH PRIORITY ^^)

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-backend#22]
### It seems the order router dont like BNB and WBNB for some reason.

**_This is a problem because it means people cannot buy VRTK_**

- Trying to swap with BNB returns an error
- Console says JSON rpc error too
- Have tried with 0.1% slippage and max slippage of 49%. No dice.
- WBNB also has the same problem on the swapper. Can't buy it or sell it.

![image](https://user-images.githubusercontent.com/106936065/216992954-2e8ed30c-3a29-47f8-abc4-75aa387eff9a.png)
![image](https://user-images.githubusercontent.com/106936065/216827506-60c89ad7-c669-463e-b5fa-1557ac4bd04d.png)
![image](https://user-images.githubusercontent.com/106936065/216827520-134bdbde-bc92-4e81-ac89-c27eb2eef60f.png)
![image](https://user-images.githubusercontent.com/106936065/216827536-6d939ccd-327a-4ce6-9d64-9c4adc025137.png)

**Comment by 0xBriz** [comment]
WBNB issue is taken care of. Working on the native part. It is related to the order router setup and native BNB. Will get it sorted out.

**Comment by 0xBriz** [comment]
Closing since all falls under [https://github.com/vertekfi/dex-backend/issues/16](url) and is being worked on
