### ISSUE TITLE
Voting for all pools errors out.

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-backend#24]
**Voting is broken again, for all pools this time. Clicking **Confirm Vote** does nothing and console errors out.**

_This is top priority since the next epoch is coming._

NOTE: This connected wallet did vote for wAALTO pool before. And perhaps thats why. Other users were able to vote for any pool just fine, including the new wAALTO pool. Only users who voted for the old wAALTO pool experience this. Which means we will have to give them a link to a page with just 1 button to remove their vote from that pool once it expires.

Additional Note: The console error says something about user using too much power

![image](https://user-images.githubusercontent.com/106936065/217147508-8d459648-5fe8-4d5e-b600-c159e7d0e4e0.png)

Console Error:
![image](https://user-images.githubusercontent.com/106936065/217147527-f4b51cca-a2a1-47b2-aa07-f2ba8401c3c1.png)
![image](https://user-images.githubusercontent.com/106936065/217259864-40c70a61-23aa-40bc-8472-1f2efa2f7029.png)

**Comment by 0xBriz** [comment]
We've identified this is an issue caused by removing the previous wAalto pool and gauge. UI is not accounting for votes given to that gauge by a user, and shows their remaining votes to use as higher than they actually are. Looking for a patch up but this will take care of itself within days.
