### ISSUE TITLE
Swaps not showing up on pool pages

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-backend#26]
Moved this to here from f.e issues git.

![image](https://user-images.githubusercontent.com/106936065/217868833-08dc6ef8-07ca-4c42-9758-9db20d087336.png)

**Comment by 0xBriz** [comment]
![image](https://user-images.githubusercontent.com/98397602/218269094-6d5c5874-b3db-4f0a-b997-14f172095e72.png)
