### ISSUE TITLE
Wrong tokens in Lion's Den

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-backend#5]
![image](https://user-images.githubusercontent.com/106936065/214829906-0764ace0-6eee-4477-beaf-2cdddd67c2b2.png)

Lions Den pool is supposed to be LSHARE-DAI and not LION-DAI.

Here are the specs: 

Pool Name: Lion's Den
Pool Type: Weighted Pool
Composition: 70% LSHARE | 30% DAI
Swap Fee: 1%
Gauge Deposit Fees: 1%/1%

Target starting price for LSHARE: $5

**Comment by 0xBriz** [comment]
Taken care of. Was a pool creation issue. The pool was recreated and old one is filtered out of results.
