### ISSUE TITLE
Pools missing from Earn, Voting & Claim Page

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-backend#8]
These pools are missing from the **Earn**, **Vote** and **Claim** pages and do not show up on the UI there:

**BNB-BUSD** (CZ's Favorite Pool)
**SHDB-CHAM-BNB** (Shield of Seigniorage) 

This is a problem coz they wont be able to be voted for, and bnb-busd is a pretty important pool

EDIT: The **BTC-ETH-BNB** (Blue Chip Buffet) pool is also missing from **Earn** page

**Comment by 0xBriz** [comment]
Taken care of. We can resolve the SHDB-CHAM-BNB issue then
