### ISSUE TITLE
Incorrect Swap Fees

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-backend#9]
These pools have incorrect swap fees at the moment:

- **wAALTO/BUSD:** should be 15%
- **BUSD/USDC/USDT:** should be 0.02%
- **DAI/FRAX/TUSD/BUSD:** should be 0.02%
- **SWDB/ETH:** should be 0.5%
- **SHDB/CHAM/BNB:** should be 0.5%

**Comment by 0xBriz** [comment]
Updated
